### ISSUE TITLE
Prepare a bugfix-only 4.1.4 release?

### ISSUE THREAD

**Issue by zorun** [spiral-project/ihatemoney#588]
Currently, the latest release 4.1.3 is broken for new installs (#540).

The new 5.0.0 release (#570) might still take some time to happen (fix pending issues, wait for translators to pick up new strings, etc). In addition, it drops support for python 2 and python 3.5, so even in the long run some people may not be able to switch to 5.0.0 immediately.

Thus, I would like to propose a new "stable" 4.1.4 release, based on 4.1.3 instead of master, that fixes the following issues with 4.1.3 (checked items are already part of the [WIP branch](https://github.com/zorun/ihatemoney/tree/prepare_4_1_4)):

- [x] Fix failed installation because dependencies were not being pinned (#540, #545, #558)
- [X] Fix compatibility with werkzeug 1.0 (#488)
- [X] backend: Trim usernames to remove leading or trailing spaces. This avoids a situation where different names can be visually identical (#367)
- [X] backend: Fix API to forbid project creation when the `ALLOW_PUBLIC_PROJECT_CREATION` setting is set to false (#496)
- [X] backend: Fix crash when a localized email template is missing (#592)
- [X] backend: Fix language code parsing (#589)
- [x] backend: Improve error handling when sending emails (#595)
- [X] UI: Fix datepicker that was being displayed twice on some browsers (#221)
- [X] UI: Fix "Submit and add a new one" button that had no effect when adding a bill (#498)
- [X] UI: Prevent bill cancellation when cancelling autocomplete (#506)
- [X] UI: Fix responsive width of homepage on small screns (#549)
- [X] UI: Fix color of the "Add a member" button (#499)
- [X] UI: Fix missing HTML tag (#583)
- [X] UI: Fix a small typo in the french project-reminder email (#486)
- [X] UI: Fix typo on message displayed when adding a member (#575)
- [X] Add translations for German, Spanish, Norwegian, and Indonesian
- [x] Add translation for Russian
- [X] Update translations for all languages

Any other fix I may have missed?

What do you think on principle? @almet @JocelynDelalande @0livd  @eMerzh @Natim @Glandos  (I hope I didn't forget anybody)

**Comment by eMerzh** [comment]
i  👍 that :) 
quickly checked and your summary cherry-picks are good for me.

**Comment by zorun** [comment]
Cool :)

I have started preparing a WIP branch here: https://github.com/zorun/ihatemoney/tree/prepare_4_1_4

I found a few more fixes that could be backported, but it's still missing dependency pinning and translations for now.

**Comment by zorun** [comment]
It turns out that there were many more small fixes than I thought... I have edited the list in the first comment.

Currently missing are: proper dependency pinning (does anyone want to work on backporting this?), email error handling, Russian translation.

Two tests are failing with python2 while everything passes with python3, I'll have to investigate:

- BudgetTestCase.test_invite: `AssertionError: u'You either provided a bad token' not found in output`
- BudgetTestCase.test_login_throttler: `AssertionError: u'Too many failed login attempts, please retry later.' not found in output`

**Comment by indatwood** [comment]
I'm not sure if you found your way with the error you mentionned. @Natim fixed it in https://github.com/spiral-project/ihatemoney/commit/53dae96bdbfcf09f4cef56afda8a7ad567458eeb

**Comment by zorun** [comment]
@indatwood I had not found it, and it works, thanks!

I just finished pinning/fixing dependencies and backported the Russian translation.

Should I just create a new branch (let's say `stable-4.1`) positioned on `4.1.3` and open a PR against this branch? The goal is to let the CI run through the PR, iterate on any necessary changes, and finally merge it.

**Comment by zorun** [comment]
With #595 merged and backported this is ready to go!

@Glandos @Natim what do you think of creating a `stable-4.1` branch? Once it's done, I will be able to open a PR to merge my [4.1.4 branch](https://github.com/zorun/ihatemoney/tree/prepare_4_1_4)

**Comment by zorun** [comment]
Ping @Glandos @Natim

**Comment by Glandos** [comment]
Branch created from tag 4.1.3. @zorun has write access in the mean time, waiting for joining the right team.
And thanks for maintaining this branch!

**Comment by zorun** [comment]
Thanks for the branch creation @Glandos  !

The pull request is here, hopefully final (I may still update translations if some fixes are made in master before releasing): #640

Reviews and tests are welcome, but please don't merge yet (and especially **don't merge-squash it** ;-) ).
I plan to upgrade my server to 4.1.4 as a final test. And then hopefully release this week-end!

**Comment by zorun** [comment]
Just built a local wheel file and upgraded my server with it (python 3.7 on Debian buster): the upgrade went well, and everything seems fine!

**Comment by zorun** [comment]
I have just merged #640 !

@Glandos I don't have the rights on pypi, how should we go about it? Could you publish the release?

**Comment by Glandos** [comment]
Sorry, I can't do this. Only @almet @JocelynDelalande or @Natim 
But I'll be glad to be a maintainer on PyPI :)

**Comment by zorun** [comment]
Thanks @Glandos 

@almet @JocelynDelalande @Natim I don't like to prod people, but how do we move forward? Could you release 4.1.4? Should @Glandos and/or me get access to the pypi package to make the release?

There seemed to be interest in this release and no opposition. I have spent several hours on this and it was a good opportunity to contribute again to IHM after several years, but I would be glad it it was not done for nothing in the end... (I know that this kind of "too much time has been invested to stop now" argument is not always relevant, but it's also a question of motivation)

As a reminder, the main motivation is that the current latest release, 4.1.3, still cannot be installed. The 5.0 release is not yet ready, hence the need for this interim release 4.1.4. It also fixes minor bugs in 4.1.3.

**Comment by indatwood** [comment]
Hi, I've asked to @almet IRL and he added "Glandos" to the maintainers. Hope that's the right nickname @Glandos?

We should be good to go!

**Comment by zorun** [comment]
Thanks a lot! <3

**Comment by Natim** [comment]
Sorry I totally missed your message requesting my help :(
